version: "latest"
services:
  gophKeeperServer:
    image: keeper_server
    environment:
      SECRET_KEY: "someSecretKey"
      POSTGRES_DSN: "postgres://admin:1234@localhost:5432/test?sslmode=disable"
      SALT: "someSalt"
      RUN_ADDRESS: "http://127.0.0.1:8080"
      MINIO_ACCESS_KEY_ID: "minioServer"
      MINIO_SECRET_KEY_ID: "minioServer123"
      MINIO_ENDPOINT: "127.0.0.1:9001"
    ports:
      - "8080:8080"
    command: /app

    depends_on:
      - minioServer
      - postgresServer

  postgresServer:
    image: postgres:latest
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"


  minioClient:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio-storage:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3


  minioServer:
    image: minio/minio:latest
    command: server --console-address ":9091" --address ":9090" /data/
    ports:
      - "9090:9090"
      - "9091:9091"
    environment:
      MINIO_ROOT_USER: minioServer
      MINIO_ROOT_PASSWORD: minioServer123
    volumes:
      - minio-storage:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio-storage:

#// urlExample := "postgres://username:password@localhost:5432/database_name"