version: "latest"

services:
  gophKeeperClient:
    container_name: gophKeeperClient
    image: keeper_client
    command: tail -F anything
    environment:
      POSTGRES_DSN: "postgres://admin:1234@postgresClient:5431/test?sslmode=disable"
      SERVER_ADDRESS: "gophKeeperServer:8080"
      MINIO_ACCESS_KEY_ID: "minio"
      MINIO_SECRET_KEY_ID: "minio123"
      MINIO_ENDPOINT: "minioClient:9000"
      BUCKET_NAME: "some-bucket"
    networks:
      - keeper_network

  gophKeeperServer:
    container_name: gophKeeperServer
    image: keeper_server
    environment:
      SECRET_KEY: "someSecretKey"
      POSTGRES_DSN: "postgres://admin:1234@postgresServer:5432/test?sslmode=disable"
      SALT: "someSalt"
      RUN_ADDRESS: "gophKeeperServer:8080"
      MINIO_ACCESS_KEY_ID: "minioServer"
      MINIO_SECRET_KEY_ID: "minioServer123"
      MINIO_ENDPOINT: "minioServer:9001"
    ports:
      - "8080:8080"
    depends_on:
      - minioServer
      - postgresServer
    networks:
      - keeper_network

  postgresClient:
    container_name: postgresClient
    image: postgres:latest
    command: -p 5431
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5431:5431"
    networks:
      - keeper_network

  postgresServer:
    container_name: postgresServer
    image: postgres:latest
    command: -p 5432
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5432:5432"
    networks:
      - keeper_network

  minioClient:
    container_name: minioClient
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio-storage:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - keeper_network

  minioServer:
    container_name: minioServer
    image: minio/minio:latest
    command: server --console-address ":9091" --address ":9090" /data/
    ports:
      - "9090:9090"
      - "9091:9091"
    environment:
      MINIO_ROOT_USER: minioServer
      MINIO_ROOT_PASSWORD: minioServer123
    volumes:
      - minio-storage:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - keeper_network

volumes:
  minio-storage:

networks:
  keeper_network:
    name: keeper_network
    external: true
